version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/ubuntu/Containers/Code-Server/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped